localDynamicData = {
	"variationName": "PL_01",
	"campaignName": "PL",
	"dimensionName": {
		"160x600": "Tesa_Click_160x600_PL",
		"300x600": "Tesa_Click_300x600_PL",
		"300x250": "Tesa_Click_300x250_PL",
		"728x90": "Tesa_Click_728x90_PL"
	},
	"text1": "./text1.png",
	"highlight1": "./highlight1.png",
	"text2": "./text2.png",
	"highlight2": "./highlight2.png",
	"text3": "./text3.png",
	"highlight3": "./highlight3.png",
	"text4": "./text4.png",
	"highlight4": "./highlight4.png",
	"text5": "./text5.png",
	"highlight5": "./highlight5.png",
	"text6": "./text6.png",
	"highlight6": "./highlight6.png",
	"logo": "./logo.svg",
	"tadaa": "./tadaa.svg",
	"bg1": "./bg1.jpg",
	"bg2": "./bg2.jpg",
	"bg3": "./bg3.jpg",
	"bg4": "./bg4.jpg",
	"product": "./product_middle.png",
	"badge": "./badge.png",
	"cta": "./cta.png",
	"ctaBorder": "./cta_border.png"
}