localDynamicData = {
	"variationName": "GER_01",
	"campaignName": "GER",
	"dimensionName": {
		"200x600": "tSBS_43_Consideration_Wide_Skyscraper_",
		"300x250": "tSBS_40_Consideration_MediumRectangle_",
		"728x90": "tSBS_46_Consideration_Leaderboard_"
	},
	"text1": "./text1.png",
	"highlight1": "./highlight1.png",
	"text2": "./text2.png",
	"highlight2": "./highlight2.png",
	"text3": "./text3.png",
	"highlight3": "./highlight3.png",
	"logo": "./logo.svg",
	"tadaa1": "./tadaa_t.svg",
	"tadaa2": "./tadaa_a.svg",
	"tadaa3": "./tadaa_d.svg",
	"tadaa4": "./tadaa_a.svg",
	"tadaa5": "./tadaa_a.svg",
	"tadaa6": "./tadaa_questionmark.svg",
	"tesa": "./tesa.svg",
	"tadaa": "./tadaa.svg",
	"bg1": "./bg1.jpg",
	"bg2": "./bg2.jpg",
	"bg3": "./bg3.jpg",
	"product": "./product_middle.png",
	"productLeft": "./product_left.png",
	"productRight": "./product_right.png",
	"cta": "./cta.png",
	"ctaBorder": "./cta_border.png"
}